'use strict';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d');

let selected=0,session={version:1,createdAt:new Date().toISOString(),settings:{width:W,height:H,objectRadius:R,speed,deadzone,sampleIntervalMs:10,gapWidth,barThickness:22,barIntervalMs:2200,barSpeed:170},records:[]},run=null,replay=null,playing=false,position=0,last=performance.now(),keys=new Set(),rtHeld=false,sessionStarted=false,practice={...origin},latestInput={rawX:0,rawY:0,rt:0,source:'keyboard'};
definitions.forEach((d,i)=>{const b=document.createElement('button');b.className='mission';b.innerHTML=`<span>MISSION 0${i+1}</span>${d.name}`;b.onclick=()=>{if(run)return notice('진행 중인 미션을 먼저 제출하거나 전체 초기화하세요.');selected=i;replay=null;playing=false;update();};$('missions').append(b)});
function notice(s){$('notice').textContent=s}
function update(){document.querySelectorAll('.mission').forEach((b,i)=>b.classList.toggle('active',i===selected));const practicing=!sessionStarted&&!replay;$('title').textContent=practicing?'패드 감도 연습':definitions[selected].name;$('description').textContent=practicing?'RS로 자유롭게 움직이며 감도를 확인하세요. 연습은 기록되지 않습니다. RT를 누르면 선택한 미션을 원점에서 시작합니다.':definitions[selected].description;$('start').disabled=true;$('start').textContent='RT로 시작';$('mode').textContent=replay?'REPLAY SESSION':practicing?'PRACTICE · 기록 안 함':'LIVE SESSION';}
function start(){if(run)return;$('completion').hidden=true;sessionStarted=true;practice={...origin};replay=null;playing=false;const d=definitions[selected];run={mission:selected,name:d.name,startedAt:new Date().toISOString(),durationMs:0,samples:[],bars:[],x:origin.x,y:origin.y,elapsed:0,nextSample:0,waypoint:1,errorSum:0,errorCount:0,passed:0,collisions:0};if(d.game){for(let i=0;i<10;i++)run.bars.push({id:i,spawnMs:1000+i*2200,gap:90+Math.random()*((d.axis==='x'?W:H)-180),collided:false,passed:false});}notice(d.game?'회피 기록 중 · 막대 10개를 통과하세요.':'기록 중 · 도착점에서 RT로 제출하세요.');sample(latestInput.rawX,latestInput.rawY,0,0);update()}
function segmentDistance(x,y,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy)));return Math.hypot(x-a[0]-t*dx,y-a[1]-t*dy)}
function errorAt(d,x,y){return Math.min(...d.path.slice(1).map((b,i)=>segmentDistance(x,y,d.path[i],b)))/Math.hypot(W,H)*100}
function sample(rx,ry,ax,ay){const d=definitions[selected];const s={t:Math.round(run.elapsed),rawX:rx,rawY:ry,inputX:ax,inputY:ay,x:run.x,y:run.y,waypoint:run.waypoint,rt:latestInput.rt,inputSource:latestInput.source,virtualGamepad:window.virtualGamepad.snapshot(),bars:run.bars.map(b=>({...b}))};run.samples.push(s);if(!d.game){run.errorSum+=errorAt(d,run.x,run.y);run.errorCount++}}
function submit(){if(!run||replay)return;const d=definitions[selected];if(d.game&&run.passed<10)return;const end=d.path?.at(-1);const success=d.game?run.collisions===0:run.waypoint===d.path.length&&Math.hypot(run.x-end[0],run.y-end[1])<=26;sample(latestInput.rawX,latestInput.rawY,0,0);session.records.push({mission:selected,name:d.name,startedAt:run.startedAt,durationMs:Math.round(run.elapsed),speed,gapWidth,path:d.path?.map(p=>[...p]),success,errorRate:d.game?run.collisions/10*100:run.errorSum/run.errorCount,collisions:run.collisions,passed:run.passed,bars:run.bars.map(b=>({...b})),samples:run.samples});run=null;notice(success?'미션 성공 · 기록이 저장되었습니다.':'미션 제출 완료 · 목표 미달 또는 충돌이 기록되었습니다.');const hasNext=selected<definitions.length-1;if(hasNext)selected++;renderRecords();update();if(hasNext&&!definitions[selected].game)start();else if(hasNext)notice('기록이 저장되었습니다. RT로 다음 회피 미션을 시작하세요.');else{$('completion').hidden=false;notice('전체 녹화 완료 · 기록을 다운로드하거나 리플레이 페이지에서 확인하세요.');}}
function renderRecords(){$('resultList').replaceChildren();session.records.forEach((r,i)=>{const row=document.createElement('div');row.className='result';for(const value of [`${i+1}. ${r.name}`,`${(r.durationMs/1000).toFixed(1)}초 · 오차 ${r.errorRate.toFixed(2)}%`,r.success?'성공':'실패']){const el=document.createElement('span');el.textContent=value;row.append(el)}$('resultList').append(row)})}
function input(){const pads=navigator.getGamepads?.()||[],pad=Array.from(pads).find(Boolean);$('connection').textContent=pad?'게임패드 연결됨':'키보드 사용 가능 · 게임패드 대기';const virtual=window.virtualGamepad;let rx=virtual.enabled?virtual.rs.x:(pad?.axes[2]||0),ry=virtual.enabled?virtual.rs.y:(pad?.axes[3]||0);if(!virtual.enabled&&keys.size){rx=Number(keys.has('ArrowRight'))-Number(keys.has('ArrowLeft'));ry=Number(keys.has('ArrowDown'))-Number(keys.has('ArrowUp'))}const pressed=virtual.enabled?virtual.rt>0:(pad?.buttons[7]?.value||0)>.5||keys.has('Enter');$('connection').textContent=virtual.enabled?'가상 게임패드 사용 중':pad?'게임패드 연결됨':'키보드 사용 가능 · 게임패드 대기';const virtualPress=virtual.enabled&&virtual.consumeRTPress();latestInput={rawX:rx,rawY:ry,rt:virtual.enabled?Math.max(virtual.rt,Number(virtualPress)):Math.max(pad?.buttons[7]?.value||0,Number(keys.has('Enter'))),source:virtual.enabled?'virtual':keys.size?'keyboard':pad?'gamepad':'keyboard'};if(((pressed&&!rtHeld)||virtualPress)&&!replay){if(!run&&$('completion').hidden)start();else if(run&&!definitions[selected].game)submit();}rtHeld=pressed;const normalize=v=>Math.abs(v)<deadzone?0:Math.sign(v)*(Math.abs(v)-deadzone)/(1-deadzone);return [rx,ry,normalize(rx),normalize(ry)]}
function tick(dt,values){const d=definitions[selected];let [rx,ry,ax,ay]=values;if(d.axis==='x')ay=0;if(d.axis==='y')ax=0;const length=Math.hypot(ax,ay);if(length>1){ax/=length;ay/=length}run.elapsed+=dt;run.x=Math.max(R,Math.min(W-R,run.x+ax*speed*dt/1000));run.y=Math.max(R,Math.min(H-R,run.y+ay*speed*dt/1000));if(d.game){for(const b of run.bars){const p=barPosition(d,b,run.elapsed),coord=d.axis==='x'?run.y:run.x,across=d.axis==='x'?run.x:run.y;if(run.elapsed>=b.spawnMs&&Math.abs(p-coord)<=R+11&&Math.abs(across-b.gap)>gapWidth/2-R&&!b.collided){b.collided=true;run.collisions++}if(!b.passed&&(d.axis==='x'?p>coord+R+11:p<coord-R-11)&&run.elapsed>=b.spawnMs){b.passed=true;run.passed++}}}else if(run.waypoint<d.path.length){const p=d.path[run.waypoint];if(Math.hypot(run.x-p[0],run.y-p[1])<=26)run.waypoint++}if(run.elapsed>=run.nextSample){sample(rx,ry,ax,ay);run.nextSample=run.elapsed+10}if(d.game&&run.passed===10)submit()}
function practiceTick(dt,values){
  let ax=values[2],ay=values[3];const length=Math.hypot(ax,ay);if(length>1){ax/=length;ay/=length;}
  practice.x=Math.max(R,Math.min(W-R,practice.x+ax*speed*dt/1000));
  practice.y=Math.max(R,Math.min(H-R,practice.y+ay*speed*dt/1000));
}
function drawPractice(){
  ctx.fillStyle='#69798c';ctx.font='16px sans-serif';ctx.textAlign='center';
  ctx.fillText('감도 연습 · RS로 자유 이동 / RT로 미션 시작',W/2,42);
  ctx.fillStyle='#8396a7';ctx.font='12px sans-serif';ctx.fillText('최대 속도 400px/초 · 데드존 12% · 기록 안 함',W/2,66);
  ctx.beginPath();ctx.arc(origin.x,origin.y,5,0,Math.PI*2);ctx.fillStyle='#b5ccc8';ctx.fill();
  ctx.beginPath();ctx.arc(practice.x,practice.y,R,0,Math.PI*2);ctx.fillStyle='#237d73';ctx.fill();ctx.lineWidth=3;ctx.strokeStyle='white';ctx.stroke();
  $('elapsed').textContent='0.0초';$('error').textContent='—';$('status').textContent='감도 연습';$('bars').textContent='—';
}
function draw(){if(!sessionStarted&&!replay){ctx.clearRect(0,0,W,H);drawPractice();return}drawMission({selected,run,replay,position,session});}
function frame(now){const dt=Math.min(50,now-last);last=now;const values=input();if(!document.hidden){if(run)tick(dt,values);else if(!sessionStarted&&!replay)practiceTick(dt,values);}if(replay&&playing){position=Math.min(replay.durationMs,position+dt);if(position===replay.durationMs){playing=false;$('play').textContent='재생'}}draw();requestAnimationFrame(frame)}
$('start').onclick=start;$('reset').onclick=()=>{if((run||session.records.length)&&!confirm('진행 중인 미션과 모든 기록을 삭제할까요?'))return;run=null;replay=null;playing=false;session.records=[];$('completion').hidden=true;session.createdAt=new Date().toISOString();selected=0;sessionStarted=false;practice={...origin};renderRecords();update();notice('감도 연습 중 · RT를 누르면 원점에서 첫 미션을 시작합니다.')};
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('download').onclick=()=>download('gamepad-session.json',JSON.stringify(session,null,2),'application/json');$('csv').onclick=()=>{const rows=['record,mission,time_ms,raw_x,raw_y,input_x,input_y,x,y,error_rate,success,rt,virtual_enabled'];session.records.forEach((r,i)=>r.samples.forEach(s=>rows.push([i+1,r.mission+1,s.t,s.rawX,s.rawY,s.inputX,s.inputY,s.x,s.y,r.errorRate,r.success,s.rt??s.virtualGamepad?.rt??0,s.virtualGamepad?.enabled??false].join(','))));download('gamepad-input.csv','\uFEFF'+rows.join('\r\n'),'text/csv;charset=utf-8')};
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Enter'].includes(e.key)&&!['INPUT','SELECT','BUTTON'].includes(e.target.tagName)){e.preventDefault();keys.add(e.key)}});window.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>keys.clear());update();notice('감도 연습 중 · RS로 조작감을 확인한 뒤 RT로 미션을 시작하세요.');requestAnimationFrame(frame);

$('downloadCompleted').onclick=$('download').onclick;
async function openReplay(){if(run)return notice('진행 중인 미션을 먼저 완료하세요.');if(!session.records.length){location.href='replay.html';return}try{await sessionStore.save(session);location.href='replay.html';}catch{notice('페이지 간 기록 전달에 실패했습니다. JSON을 다운로드한 뒤 리플레이 페이지에서 불러오세요.');}}
$('openReplay').onclick=openReplay;$('replayCompleted').onclick=openReplay;
